#+title:  How to build and run the emacs customization kit


* What you need to already have on your machine

 - ~emacs-25.x~ is installed :: emacs-24 will not work.

 - ~org-version~ is less than 9.x :: ~emacs-25.2.2~ comes
      with ~org-version 8.2.10~ by default.  (This may not
      be true with later versions of ~emacs~, though.).  

* How to install the customization kit

 - 1. Clone the repository and =cd= into the working copy
   directory:

#+BEGIN_EXAMPLE
git clone  https://gitlab.com/vxcg/prj/emacs/emacs.git
cd emacs
#+END_EXAMPLE


 - 2. Run the makefile:

#+BEGIN_EXAMPLE
make -k all
#+END_EXAMPLE

   
 
* What happens after a successful install of the customization kit

Inside your emacs working copy:

 - ~build~ :: directory is generated
 - ~build/docs~ :: holds the html docs
 - ~build/code~ :: holds the code 
 - ~build/code/init.el~ :: is the emacs init file

* How to launch emacs with the customization kit
From the command line from any directory, type
#+BEGIN_SRC bash :eval no
emacs -q -l /path/to/emacs-working-copy/build/code/init.el
#+END_SRC

The =-q= and =-l= combination ensures that emacs starts with
no other init file other than the one specified by the =-l=
flag, so if you already have any previous customizations,
e.g., in a =.emacs.d= directory, they will be ignored.  This
customization kit works stand alone.  

* How to include your  existing customizations with the kit

If you wish to load your own or existing customizations,
it's possible to open it in a buffer and load them.
However, this opens up the possibility of a broken emacs
customization, specially if some global directory variables
like =load-path= or =user-emacs-directory= are modified.
So, Caveat Emptor!




* How to delete the customization kit

From the command line, type

#+BEGIN_SRC bash :eval no
\rm -rf /path/to/emacs-working-copy
#+END_SRC

* Package installed via the customization kit

Note that any packages or any further customizations that
you install when using this customizations will sit under
the =elpa= subdirectory of =build/code=.  They will get
deleted when you delete the customization kit.
