#+title:  Setting up journaling and org-capture

* What is a journal?

A journal is a diary or log of all the things you have done
in an entire year.  There is an entry (heading) for each day
of the year.  Under that heading you can record all the
stuff that you did on that day.  Such a structure is called
a date-tree in org-mode. 

Org-mode lets you manage journals by editing date trees. 


** A journal file

A journal file is a file that has entries for
each date.  An example of a journal file is
[[./2017-journal.org]].

** Creating a journal file automatically

You might want to create an entire journal file
automatically.  Here is the code that does it.  Put it in
your emacs init file. 

#+BEGIN_SRC elisp  :tangle journal.el

;;; Journal

;;; (require 'org-journal)

;;;  Date Tree
;;; https://lists.gnu.org/archive/html/emacs-orgmode/2010-07/msg01056.html
;;; Creating a template
;;;;; Elisp code follows:


(defun create-dates-for-month-and-year (month year)
  "Create entries in date-tree format in current buffer.

 This function creates nodes for all days in given the given 
 MONTH and YEAR in the current buffer 
 (if they do not exist already).

"
  (let ((day 1)
        (max-days (if (= 2 month)
                        (if (date-leap-year-p year) 29 28)
                      (nth month
                           (list nil 31 28 31 30 31 30 31 31 30 31 30 31)))))
    (while (<= day max-days)
      (org-datetree-find-date-create (list month day year))
      (setq day (+ 1 day))
      )))

(defun create-dates-for-year (year)
  "Create entries in date-tree format in current buffer.

 This function creates nodes for all days in given YEAR
 in the current buffer (if they do not exist already).

"
  (let ((month 1))
    (while (<= month 12)
      (create-dates-for-month-and-year month year)
      (setq month (+ 1 month))
      )))
#+END_SRC


** Adding entries into a journal file

You can add as many entries as you like under a date
heading.  Each entry is best written a subheading.

E.g., 

#+BEGIN_EXAMPLE
** 2017-01 January
*** 2017-01-01 Sunday
**** Celebrated New Year day!
Went to friend's house for brunch.
**** Watched movie
**** Had dinner at restaurant
#+END_EXAMPLE

* Making entries to the journal via org-capture

Add this to your ~emacs~ init file.

#+BEGIN_SRC elisp :tangle journal.el


;;; Journal

;;; (require 'org-journal)

;;;  Date Tree
;;; https://lists.gnu.org/archive/html/emacs-orgmode/2010-07/msg01056.html
;;; Creating a template
;;;;; Elisp code follows:


(defun create-dates-for-month-and-year (month year)
  "Create entries in date-tree format in current buffer.

 This function creates nodes for all days in given the given 
 MONTH and YEAR in the current buffer 
 (if they do not exist already).

"
  (let ((day 1)
        (max-days (if (= 2 month)
                        (if (date-leap-year-p year) 29 28)
                      (nth month
                           (list nil 31 28 31 30 31 30 31 31 30 31 30 31)))))
    (while (<= day max-days)
      (org-datetree-find-date-create (list month day year))
      (setq day (+ 1 day))
      )))

(defun create-dates-for-year (year)
  "Create entries in date-tree format in current buffer.

 This function creates nodes for all days in given YEAR
 in the current buffer (if they do not exist already).

"
  (let ((month 1))
    (while (<= month 12)
      (create-dates-for-month-and-year month year)
      (setq month (+ 1 month))
      )))
#+END_SRC
